config/routes.rb
Sampleapp::Application.routes.draw do
  root :to => 'Site#index'
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new'
	match '/signout', to: 'sessions#destroy'
	resources :users
	match '/signup' => 'users#new'
  resources :products

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  value      :integer
#  time       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  cost       :integer
#  xp         :integer
#

class Product < ActiveRecord::Base
  attr_accessible :name, :time, :value, :cost, :xp
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation

  has_secure_password

	before_validation { email.downcase! }
  before_save :create_remember_token

  validates(:name, {
    presence: true,
    length: { maximum: 30 }
  })
  validates :email,
    presence: true,
    format: { with: /\A.+@[a-z\d\-.]+\z/i },
    uniqueness: true
  validates :password,
    presence: true,
    length: { minimum: 6, maximum: 255 }
  validates :password_confirmation,
    presence: true

  private
	
      def create_remember_token
        self.remember_token = SecureRandom.urlsafe_base64
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @qty = 28
		@val_p_min = (@product.value / (@product.time / 60.0)).round 2
		@total_val_p_min = (@qty * @val_p_min).round 2
		

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    # Find user by email
    user = User.find_by_email(params[:email].downcase)
    # If user was found and authenticates with give password
    if user && user.authenticate(params[:password])
      # Login success!
      # Pass user to session helper
			sign_in user
			# Redirect to user and display flash notice
			redirect_to user, notice: ["Welcome #{user.name}!"]
    else
      # Login failure :(
      # Note that error msg is a string inside of an array
      flash.now[:error] = ["Invalid login credentials."]
      render :new
    end
  end
  def destroy
    sign_out
    redirect_to users_url, notice: ["You have been successfully signed out."]
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  	@controller = params[:controller]
  	@name = :World
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end
  def new
    @user = User.new
  end
  def create
  	@user = User.create(params[:user])
  	if @user.save
  		flash[:success] = ["Sucess! Welcome to SampleApp!"]
			redirect_to @user
  	else
  		flash.now[:error] = @user.errors.full_messages
  		render :new
  	end
  end
  def edit
  end
  def show
		@user = User.find(params[:id])
  end
  def update
  end
  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    # Add user's remember token to session.
    session[:remember_token] = user.remember_token
    # Set user as current_user.
    self.current_user = user
  end

  def signed_in?
    ! current_user.nil?
  end

  def sign_out
    reset_session
    self.current_user = nil
  end

  def current_user=(u)
    # Setter for curent_user.
    @current_user = u
  end
  
  def current_user
    # Getter. Returns current_user of finds user that matches the session
    # remember token.
    #
    # NOTICE! Witout the if statement, after a user logs out, the first user
    # with a nil remember token will automatically be logged in!
    if session[:remember_token]
      @current_user ||= User.find_by_remember_token session[:remember_token]
    end
  end	
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/user_helper.rb
module UserHelper

	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = 'https://secure.gravatar.com/avatar/' + gravatar_id
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">

	<title></title>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- css -->

	<%= stylesheet_link_tag "application", :media => "all" %>

	<!-- HTML5 shim for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- icons -->
	<link rel="shortcut icon" href="assets/ico/favicon.ico">
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/ico/apple-touch-icon-144-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/ico/apple-touch-icon-114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/ico/apple-touch-icon-72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" href="/assets/ico/apple-touch-icon-57-precomposed.png">

</head>

<body>

	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<a class="brand" href="<%= root_path %>">Sample App</a>
				<div class="nav-collapse">
					<ul class="nav">
						<li class="active"><a href="<%= root_path %>">Home</a></li>
						<% if signed_in? %>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @current_user.name %> <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="<%= user_path current_user %>">Profile</a></li>
								<li><a href="<%= users_path %>">Users</a></li>
								<li><a href="#">Settings</a></li>
								<li class="divider"></li>
								<li><a href="<%= signout_path %>">Sign out</a></li>
							</ul>
						</li>
						<% else %>
						<li><a href="<%= signin_path %>">Sign in</a></li>
						<% end %>
					</ul>
				</div><!-- .nav-collapse -->
			</div><!-- .container -->
		</div><!-- .navbar-inner -->
	</div><!-- .navbar -->

	<div class="container">

	<% flash.each do |key, value|  %>
	<div class="alert alert-block alert-<%= key %>">
		<button type="button" class="close" data-dismiss="alert">×</button>
		<% value.each do |m| %>
			<p><%= m %></p>
		<% end %>
	</div>
	<% end %>

	<% #render 'shared/flash' %>

	<%= yield %>

	</div>

	<footer class="container">

    <% if Rails.env.development? %>
		<%= debug params %>
		<%= debug @current_user %>
		<%= debug session %>
		<% end %>
	
	</footer>

<!-- js -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>

</body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |key, value|  %>
<div class="alert alert-block alert-<%= key %>">
	<button type="button" class="close" data-dismiss="alert">×</button>
	<% value.each do |m| %>
		<p><%= m %></p>
	<% end %>
</div>
<% end %>

app/views/site/index.html.erb
<div class="container">
	<div class="hero-unit">
		<h1>Hello, <%= @name %>!</h1>
		<p>This is the home page for the Ruby on Rails tutorial Sample App being served up by the <%= @controller %> controller.</p>
		<p><a href="/signup" class="btn btn-primary btn-large">Sign Up &raquo;</a></p>
	</div>
</div>

app/views/user/new.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <h1>Sign Up</h1>
      <p>Sign up for a new account below.</p>
  	</div>
  </div><!-- row -->
  <div class="row">
  	<div class="span12">
      <form class="well">
        <div class="input-prepend">
          <span class="add-on">
            <i class="icon-user"></i>
          </span><input type="text" placeholder="Name">
        </div>
        <div class="input-prepend">
          <span class="add-on">
            <i class="icon-envelope"></i>
          </span><input type="text" placeholder="Email">
        </div>
        <div class="input-prepend">
          <span class="add-on">
            <i class="icon-lock"></i>
          </span><input type="password" placeholder="Password">
        </div>
        <div class="input-prepend">
          <span class="add-on">
            <i class="icon-lock"></i>
          </span><input type="password" placeholder="Password again">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
  
  	</div>
  </div><!-- row -->
</div>

app/views/users/index.html.erb
<table class="table">
	<thead>
		<tr>
			<td>ID</td>
			<td></td>
			<td>Name</td>
			<td>Email</td>
			<td>Join Date</td>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |u| %>
			<tr>
				<td><%= u.id %></td>
				<td>
					<a href="/users/<%= u.id %>">
						<img src="<%= gravatar_for u %>" alt="gravatar" class="gravatar" style="border-radius: 99999px; height: 20px">
					</a>
				</td>
				<td><%= u.name %></td>
				<td><%= u.email %></td>
				<td><%= u.created_at.strftime "%m/%d/%y" %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <h1>Sign Up</h1>
      <p>Sign up for a new account below.</p>
  	</div>
  </div><!-- row -->
  <div class="row">
  	<div class="span12">
      <form class="well" action="/users" method="post" accept-charset="UTF-8">
        <div class="input-prepend">
          <span class="add-on">
            <i class="icon-user"></i>
          </span><input type="text" placeholder="Name" name="user[name]">
        </div>
        <div class="input-prepend">
          <span class="add-on">
            <i class="icon-envelope"></i>
          </span><input type="text" placeholder="Email" name="user[email]">
        </div>
        <div class="input-prepend">
          <span class="add-on">
            <i class="icon-lock"></i>
          </span><input type="password" placeholder="Password" name="user[password]">
        </div>
        <div class="input-prepend">
          <span class="add-on">
            <i class="icon-lock"></i>
          </span><input type="password" placeholder="Password again" name="user[password_confirmation]">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
  
  	</div>
  </div><!-- row -->
</div>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<p><img src="<%= gravatar_for @user %>" alt="gravatar" class="gravatar"></p>
<p><%= @user.email %></p>